// This file is generated from .env by scripts/generate-env.js
// Do not edit this file directly.

export const dotenvEnvironment = {
  apiUrl: "https://ansurbackendnestjs-production-dc35.up.railway.app",
  apiUrlProd: "http://192.168.1.11:3000",
};
