const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const generatedPath = path.join(root, 'src', 'environments', 'environment.generated.ts');

const result = dotenv.config({ path: envPath });
const env = result.parsed || {};

const apiUrl = env.NG_APP_API_URL_DEV || process.env.NG_APP_API_URL_DEV || process.env.API_URL || 'http://localhost:3000';
const apiUrlProd = env.NG_APP_API_URL_PROD || process.env.NG_APP_API_URL_PROD || process.env.API_URL_PROD || 'https://api.ansur.com.pe';

const generatedContent = `// This file is generated from .env by scripts/generate-env.js
// Do not edit this file directly.

export const dotenvEnvironment = {
  apiUrl: ${JSON.stringify(apiUrl)},
  apiUrlProd: ${JSON.stringify(apiUrlProd)},
};
`;

fs.writeFileSync(generatedPath, generatedContent, { encoding: 'utf8' });
console.log(`Environment constants written to ${generatedPath}`);
